name: Full Deployment (Web & Android)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # JOB 1: Build & Deploy Website
  deploy-web:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CUBIC }}'
          channelId: live
          projectId: kasir-cubic
        continue-on-error: true

  # JOB 2: Build APK Android (RELEASE)
  build-android:
    name: Build Android APK Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Sinkronisasi Capacitor
        run: npx cap sync android

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Run Signing Report (Untuk Ambil SHA-1)
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew signingReport
        env:
          KEYSTORE_PATH: release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build APK (Mode Release)
        working-directory: ./android
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK ke Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CUBIC-RELEASE-APK
          path: android/app/build/outputs/apk/release/app-release.apk
